# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bot/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(93, 93, 93);\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: none;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(self.frame)
        self.menu.setMinimumSize(QtCore.QSize(0, 0))
        self.menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.btnConfiguracao = QtWidgets.QPushButton(self.menu)
        self.btnConfiguracao.setGeometry(QtCore.QRect(10, 422, 41, 31))
        font = QtGui.QFont()
        font.setFamily("MS Outlook")
        self.btnConfiguracao.setFont(font)
        self.btnConfiguracao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnConfiguracao.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.btnConfiguracao.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img_rc/bot/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConfiguracao.setIcon(icon)
        self.btnConfiguracao.setIconSize(QtCore.QSize(23, 23))
        self.btnConfiguracao.setObjectName("btnConfiguracao")
        self.btnIniciar = QtWidgets.QPushButton(self.menu)
        self.btnIniciar.setGeometry(QtCore.QRect(10, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.btnIniciar.setFont(font)
        self.btnIniciar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnIniciar.setStyleSheet("background-color: rgb(117, 117, 117);")
        self.btnIniciar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img_rc/bot/on-off-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIniciar.setIcon(icon1)
        self.btnIniciar.setIconSize(QtCore.QSize(23, 23))
        self.btnIniciar.setObjectName("btnIniciar")
        self.horizontalLayout.addWidget(self.menu)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.btnMenu = QtWidgets.QPushButton(self.frame_3)
        self.btnMenu.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.btnMenu.setFont(font)
        self.btnMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMenu.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img_rc/bot/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu.setIcon(icon2)
        self.btnMenu.setIconSize(QtCore.QSize(16, 16))
        self.btnMenu.setObjectName("btnMenu")
        self.gridLayout.addWidget(self.btnMenu, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setStyleSheet("background-color: rgb(93, 93, 93);\n"
"")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(140, -110, 711, 541))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_5 = QtWidgets.QFrame(self.page)
        self.frame_5.setGeometry(QtCore.QRect(39, 339, 491, 51))
        self.frame_5.setStyleSheet("alternate-background-color: none;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelSinais = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(15)
        self.labelSinais.setFont(font)
        self.labelSinais.setStyleSheet("background-color: none;")
        self.labelSinais.setText("")
        self.labelSinais.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSinais.setObjectName("labelSinais")
        self.gridLayout_3.addWidget(self.labelSinais, 0, 0, 1, 1)
        self.btnContraTendencia = QtWidgets.QPushButton(self.page)
        self.btnContraTendencia.setGeometry(QtCore.QRect(410, 300, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btnContraTendencia.setFont(font)
        self.btnContraTendencia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnContraTendencia.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius: 1pix;\n"
"font-size:16pix;\n"
"background-color: rgb(255,255,0);\n"
"}\n"
"QPushButton{backgroud-color:#fff; color:black}\n"
"\n"
"QPushButton:hover { background-color: rgba(0, 0, 0, 0.5)}")
        self.btnContraTendencia.setObjectName("btnContraTendencia")
        self.btnGale = QtWidgets.QPushButton(self.page)
        self.btnGale.setGeometry(QtCore.QRect(420, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnGale.setFont(font)
        self.btnGale.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGale.setStyleSheet("QPushButton{\n"
"background-color: rgb(140, 140, 140);\n"
"border-radius: 1pix;\n"
"font-size:16pix;\n"
"background-color: rgb(140,140,140);\n"
"}\n"
"QPushButton{backgroud-color:#fff; color:black}\n"
"\n"
"QPushButton:hover { background-color: rgba(0, 0, 0, 0.5)}")
        self.btnGale.setObjectName("btnGale")
        self.btnBranco = QtWidgets.QPushButton(self.page)
        self.btnBranco.setGeometry(QtCore.QRect(70, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnBranco.setFont(font)
        self.btnBranco.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBranco.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 1pix;\n"
"font-size:16pix;\n"
"background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton{backgroud-color:#fff; color:black}\n"
"\n"
"QPushButton:hover { background-color: rgba(0, 0, 0, 0.5)}\n"
"")
        self.btnBranco.setObjectName("btnBranco")
        self.btnAlerta = QtWidgets.QPushButton(self.page)
        self.btnAlerta.setGeometry(QtCore.QRect(410, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btnAlerta.setFont(font)
        self.btnAlerta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlerta.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius: 1pix;\n"
"font-size:16pix;\n"
"background-color: rgb(255,255,0);\n"
"}\n"
"QPushButton{backgroud-color:#fff; color:black}\n"
"\n"
"QPushButton:hover { background-color: rgba(0, 0, 0, 0.5)}\n"
"")
        self.btnAlerta.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img_rc/bot/warning-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlerta.setIcon(icon3)
        self.btnAlerta.setIconSize(QtCore.QSize(32, 32))
        self.btnAlerta.setObjectName("btnAlerta")
        self.btnWin = QtWidgets.QPushButton(self.page)
        self.btnWin.setGeometry(QtCore.QRect(310, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnWin.setFont(font)
        self.btnWin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWin.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 0);\n"
"border-radius: 1pix;\n"
"font-size:16pix;\n"
"background-color: rgb(0,170,0);\n"
"}\n"
"QPushButton{backgroud-color:#fff; color:black}\n"
"\n"
"QPushButton:hover { background-color: rgba(0, 0, 0, 0.5)}")
        self.btnWin.setObjectName("btnWin")
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setGeometry(QtCore.QRect(49, 10, 471, 31))
        self.frame_4.setMinimumSize(QtCore.QSize(0, 31))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 31))
        self.frame_4.setStyleSheet("background-color: none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelBranco = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBranco.setFont(font)
        self.labelBranco.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBranco.setObjectName("labelBranco")
        self.horizontalLayout_2.addWidget(self.labelBranco)
        self.labelLoss = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelLoss.setFont(font)
        self.labelLoss.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoss.setObjectName("labelLoss")
        self.horizontalLayout_2.addWidget(self.labelLoss)
        self.labelWin = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelWin.setFont(font)
        self.labelWin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWin.setObjectName("labelWin")
        self.horizontalLayout_2.addWidget(self.labelWin)
        self.labelGale = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelGale.setFont(font)
        self.labelGale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGale.setObjectName("labelGale")
        self.horizontalLayout_2.addWidget(self.labelGale)
        self.btnRodar = QtWidgets.QPushButton(self.page)
        self.btnRodar.setGeometry(QtCore.QRect(60, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.btnRodar.setFont(font)
        self.btnRodar.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius: 1pix;\n"
"font-size:16pix;\n"
"background-color: rgb(255,255,0);\n"
"}\n"
"QPushButton{backgroud-color:#fff; color:black}\n"
"\n"
"QPushButton:hover { background-color: rgba(0, 0, 0, 0.5)}")
        self.btnRodar.setObjectName("btnRodar")
        self.btnJogaGale = QtWidgets.QPushButton(self.page)
        self.btnJogaGale.setGeometry(QtCore.QRect(410, 260, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnJogaGale.setFont(font)
        self.btnJogaGale.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnJogaGale.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius: 1pix;\n"
"font-size:16pix;\n"
"background-color: rgb(255,255,0);\n"
"}\n"
"QPushButton{backgroud-color:#fff; color:black}\n"
"\n"
"QPushButton:hover { background-color: rgba(0, 0, 0, 0.5)}")
        self.btnJogaGale.setObjectName("btnJogaGale")
        self.btnLoss = QtWidgets.QPushButton(self.page)
        self.btnLoss.setGeometry(QtCore.QRect(190, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.btnLoss.setFont(font)
        self.btnLoss.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoss.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius: 1pix;\n"
"font-size:16pix;\n"
"background-color: rgb(255,0,0);\n"
"}\n"
"QPushButton{backgroud-color:#fff; color:black}\n"
"\n"
"QPushButton:hover { background-color: rgba(0, 0, 0, 0.5)}")
        self.btnLoss.setObjectName("btnLoss")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(140, -110, 601, 481))
        self.label_2.setObjectName("label_2")
        self.btnVoltar = QtWidgets.QPushButton(self.page_2)
        self.btnVoltar.setGeometry(QtCore.QRect(0, 0, 31, 23))
        self.btnVoltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVoltar.setStyleSheet("background-color: rgb(122, 122, 122);")
        self.btnVoltar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img_rc/bot/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVoltar.setIcon(icon4)
        self.btnVoltar.setObjectName("btnVoltar")
        self.inputChaveapi = QtWidgets.QLineEdit(self.page_2)
        self.inputChaveapi.setGeometry(QtCore.QRect(160, 10, 151, 20))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.inputChaveapi.setFont(font)
        self.inputChaveapi.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.inputChaveapi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputChaveapi.setText("")
        self.inputChaveapi.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputChaveapi.setObjectName("inputChaveapi")
        self.inputChaveid = QtWidgets.QLineEdit(self.page_2)
        self.inputChaveid.setGeometry(QtCore.QRect(400, 10, 113, 20))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inputChaveid.setFont(font)
        self.inputChaveid.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.inputChaveid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputChaveid.setText("")
        self.inputChaveid.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputChaveid.setObjectName("inputChaveid")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(320, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(70, 0, 81, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.checkManterSalvo = QtWidgets.QCheckBox(self.page_2)
        self.checkManterSalvo.setGeometry(QtCore.QRect(400, 40, 70, 17))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkManterSalvo.setFont(font)
        self.checkManterSalvo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkManterSalvo.setObjectName("checkManterSalvo")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img_rc/bot/app.png\"/></p></body></html>"))
        self.btnContraTendencia.setText(_translate("MainWindow", "Contra Tendencia"))
        self.btnGale.setText(_translate("MainWindow", "Gale"))
        self.btnBranco.setText(_translate("MainWindow", "Branco"))
        self.btnWin.setText(_translate("MainWindow", "Win"))
        self.labelBranco.setText(_translate("MainWindow", "0"))
        self.labelLoss.setText(_translate("MainWindow", "0"))
        self.labelWin.setText(_translate("MainWindow", "0"))
        self.labelGale.setText(_translate("MainWindow", "0"))
        self.btnRodar.setText(_translate("MainWindow", "JOGAR"))
        self.btnJogaGale.setText(_translate("MainWindow", "JOGA-GALE"))
        self.btnLoss.setText(_translate("MainWindow", "Loss"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img_rc/bot/app.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Chat ID  :"))
        self.label_4.setText(_translate("MainWindow", "Chave API :"))
        self.checkManterSalvo.setText(_translate("MainWindow", "Salvar"))
import img_rc
