# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 438)
        MainWindow.setMinimumSize(QtCore.QSize(600, 438))
        MainWindow.setMaximumSize(QtCore.QSize(600, 438))
        MainWindow.setStyleSheet("background-color: rgb(0, 56, 83);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"\n"
"QPushButton {border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setMinimumSize(QtCore.QSize(0, 0))
        self.menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menu.setStyleSheet("QFrame {background-color: rgb(83, 93, 131);\n"
"border-radius: 5px;}\n"
"")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.btnConfiguracao = QtWidgets.QPushButton(self.menu)
        self.btnConfiguracao.setGeometry(QtCore.QRect(10, 390, 31, 23))
        self.btnConfiguracao.setObjectName("btnConfiguracao")
        self.btnIniciar = QtWidgets.QPushButton(self.menu)
        self.btnIniciar.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.btnIniciar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(80, 80, 120);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(132, 132, 132, 0.5);\n"
"}")
        self.btnIniciar.setObjectName("btnIniciar")
        self.btnParar = QtWidgets.QPushButton(self.menu)
        self.btnParar.setGeometry(QtCore.QRect(10, 40, 31, 21))
        self.btnParar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(80, 80, 120);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(132, 132, 132, 0.5);\n"
"}")
        self.btnParar.setObjectName("btnParar")
        self.horizontalLayout.addWidget(self.menu)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnMenu = QtWidgets.QPushButton(self.frame_2)
        self.btnMenu.setMinimumSize(QtCore.QSize(30, 30))
        self.btnMenu.setMaximumSize(QtCore.QSize(30, 30))
        self.btnMenu.setStyleSheet("QPushButton {\n"
"    background-color: rgb(80, 80, 120);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(132, 132, 132, 0.5);\n"
"}")
        self.btnMenu.setObjectName("btnMenu")
        self.gridLayout.addWidget(self.btnMenu, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("QLineEdit {background-color: rgb(255, 255, 255); border-radius: 5px;}\n"
"QLabel {background-color: None;\n"
"color: white;}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.btnBranco = QtWidgets.QPushButton(self.page)
        self.btnBranco.setGeometry(QtCore.QRect(70, 270, 91, 31))
        self.btnBranco.setStyleSheet("QPushButton {background-color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover {background-color: rgba(85, 255, 0, 0.9);\n"
"}\n"
"\n"
"")
        self.btnBranco.setCheckable(True)
        self.btnBranco.setDefault(False)
        self.btnBranco.setObjectName("btnBranco")
        self.btnLoss = QtWidgets.QPushButton(self.page)
        self.btnLoss.setGeometry(QtCore.QRect(300, 270, 101, 31))
        self.btnLoss.setStyleSheet("QPushButton {background-color: rgb(255, 85, 0);}\n"
"QPushButton:hover {background-color: rgba(148, 148, 148, 0.5);\n"
"}\n"
"")
        self.btnLoss.setObjectName("btnLoss")
        self.btnGale = QtWidgets.QPushButton(self.page)
        self.btnGale.setGeometry(QtCore.QRect(420, 270, 101, 31))
        self.btnGale.setStyleSheet("QPushButton {background-color: rgb(255, 255, 127);}\n"
"QPushButton:hover {background-color: rgba(85, 255, 0, 0.9);\n"
"}\n"
"")
        self.btnGale.setObjectName("btnGale")
        self.btnWin = QtWidgets.QPushButton(self.page)
        self.btnWin.setGeometry(QtCore.QRect(180, 270, 101, 31))
        self.btnWin.setStyleSheet("QPushButton {background-color: rgb(85, 170, 0);}\n"
"\n"
"QPushButton:hover {background-color: rgba(85, 255, 0, 0.9);\n"
"}")
        self.btnWin.setObjectName("btnWin")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 571, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelSinais = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelSinais.setFont(font)
        self.labelSinais.setText("")
        self.labelSinais.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSinais.setObjectName("labelSinais")
        self.gridLayout_2.addWidget(self.labelSinais, 0, 0, 1, 1)
        self.btnRodar = QtWidgets.QPushButton(self.page)
        self.btnRodar.setGeometry(QtCore.QRect(110, 70, 361, 61))
        self.btnRodar.setStyleSheet("QPushButton {background-color: rgb(255, 255, 255);}\n"
"")
        self.btnRodar.setObjectName("btnRodar")
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setGeometry(QtCore.QRect(70, 310, 451, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.labelWin = QtWidgets.QLabel(self.frame_4)
        self.labelWin.setGeometry(QtCore.QRect(116, 10, 91, 21))
        self.labelWin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWin.setObjectName("labelWin")
        self.labelBranco = QtWidgets.QLabel(self.frame_4)
        self.labelBranco.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.labelBranco.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBranco.setObjectName("labelBranco")
        self.labelLoss = QtWidgets.QLabel(self.frame_4)
        self.labelLoss.setGeometry(QtCore.QRect(240, 10, 81, 21))
        self.labelLoss.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoss.setObjectName("labelLoss")
        self.labelGale = QtWidgets.QLabel(self.frame_4)
        self.labelGale.setGeometry(QtCore.QRect(350, 10, 91, 21))
        self.labelGale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGale.setObjectName("labelGale")
        self.frame_5 = QtWidgets.QFrame(self.page)
        self.frame_5.setGeometry(QtCore.QRect(230, 160, 121, 33))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelMarque = QtWidgets.QLabel(self.frame_5)
        self.labelMarque.setText("")
        self.labelMarque.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMarque.setObjectName("labelMarque")
        self.gridLayout_3.addWidget(self.labelMarque, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.inputChaveapi = QtWidgets.QLineEdit(self.page_2)
        self.inputChaveapi.setGeometry(QtCore.QRect(140, 40, 371, 20))
        self.inputChaveapi.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputChaveapi.setObjectName("inputChaveapi")
        self.inputChatid = QtWidgets.QLineEdit(self.page_2)
        self.inputChatid.setGeometry(QtCore.QRect(140, 80, 131, 21))
        self.inputChatid.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputChatid.setObjectName("inputChatid")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.checkManterSalvo = QtWidgets.QCheckBox(self.page_2)
        self.checkManterSalvo.setGeometry(QtCore.QRect(10, 140, 91, 17))
        self.checkManterSalvo.setObjectName("checkManterSalvo")
        self.btnVoltar = QtWidgets.QPushButton(self.page_2)
        self.btnVoltar.setGeometry(QtCore.QRect(0, 10, 30, 30))
        self.btnVoltar.setMinimumSize(QtCore.QSize(30, 30))
        self.btnVoltar.setMaximumSize(QtCore.QSize(30, 30))
        self.btnVoltar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(80, 80, 120);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(132, 132, 132, 0.5);\n"
"}")
        self.btnVoltar.setObjectName("btnVoltar")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnConfiguracao.setText(_translate("MainWindow", "C"))
        self.btnIniciar.setText(_translate("MainWindow", "Iniciar"))
        self.btnParar.setText(_translate("MainWindow", "parar"))
        self.btnMenu.setText(_translate("MainWindow", "menu"))
        self.btnBranco.setText(_translate("MainWindow", "Branco"))
        self.btnLoss.setText(_translate("MainWindow", "Loss"))
        self.btnGale.setText(_translate("MainWindow", "Gale 1"))
        self.btnWin.setText(_translate("MainWindow", "Win"))
        self.btnRodar.setText(_translate("MainWindow", "Rodar"))
        self.labelWin.setText(_translate("MainWindow", "0"))
        self.labelBranco.setText(_translate("MainWindow", "0"))
        self.labelLoss.setText(_translate("MainWindow", "0"))
        self.labelGale.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Chat id"))
        self.label_8.setText(_translate("MainWindow", "Chave do bot"))
        self.checkManterSalvo.setText(_translate("MainWindow", "Manter Salvo"))
        self.btnVoltar.setText(_translate("MainWindow", "<--"))
